server:
  port: 8189
spring:
  flyway:
    locations: classpath:/db/migration
    enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          '[use_jdbc_metadata_defaults]': false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#logging:
#    level:
#      '[org.springframework.security]': DEBUG